module  org {
    module opensplice {
        module demo {

            typedef sequence<octet> OctetSequence_t;

            struct DDSFile {
                string name;
                OctetSequence_t data;
            };
            #pragma keylist DDSFile name
        };
    };
};